language: python
sudo: false
python:
- '2.7'
- '3.5'
env:
- DJANGO="django>=1.8,<1.9"
- DJANGO="django>=1.9,<1.10"
- DJANGO="django>=1.10,<1.11"
- DJANGO="django>=1.11,<2.0"
- DJANGO="django>=2.0,<2.1"
matrix:
  exclude:
  - python: '3.5'
    env: DJANGO="django>=1.8,<1.8"
  - python: '3.5'
    env: DJANGO="django>=1.9,<1.10"
  - python: '2.7'
    env: DJANGO="django>=2.0,<2.1"
before_install:
- pip install codecov
install:
- travis_retry pip install $DJANGO -e .
script:
- coverage run --source=template_analyzer runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: suUfbUtKeAzNxhhsFxKdpJ2uLf+ocGoBoQpsxLAynUWoR/qkkUancKT6dVS1zcsE9a3JRc+qE2phSz+mpiXM8TaTDE2BqYA9u22n1be/0Dt21WHwXlWDlPUEMRLz/WWguVH4t1RfkI5vCPGKlt8OueqLK0pl5QXMgL9876VwLAY=
    on_success: never
    on_failure: always
